### PR TITLE
Update NuGet packages

### PR DESCRIPTION
**Pull request by NeussConsulting**
Updated some minor package versions

### CODE REVIEW

**Comment by NeussConsulting** [comment]
Wow, what ia happening here, hundrets of failed tests on a minor version update?!

**Comment by NeussConsulting** [comment]
@jeremydmiller Had you have a look into this?
Like I said it's a Patch Version Update, which according to SemVer shouldn't have any breaking changes!

**Comment by mysticmind** [comment]
@NeussConsulting there is an existing problem with CI build with Weasel and I am yet to look at it. So it is it due to your PR changes.

I will check and pull this in.

**Review by mysticmind — APPROVED** [review]
Looks good to me.

**Comment by NeussConsulting** [comment]
It's looking, not important but it will solve Vulnerabilities.

**Comment by mysticmind** [comment]
@jeremydmiller Quick note, I have merged this PR with milestone set to 7.12.5.

@NeussConsulting This should get released in the next Weasel push.

**Pull request merged**
