### PR TITLE
Detects primary key constraint name change when migrating #39

### PR DESCRIPTION
**Pull request by tonykaralis**
- Adds missing condition for determining primary key schema change
- Assigns primary key constraint name when creating existing delta

### CODE REVIEW

**Comment by tonykaralis** [comment]
@oskardudycz mine is slightly different to yours. [Some sql code](https://github.com/JasperFx/weasel/pull/38/files#diff-46786da9918602d9f9eabf9f166f03d23ca2639a7886837fe8c2c93b86548fe0R21) what was this for?

**Comment by oskardudycz** [comment]
@tonykaralis, I didn't notice that there is an index name already in the other select. Your version is better 👍 Thanks for busting that! 🙂

**Review by oskardudycz — APPROVED** [review]

**Comment by tonykaralis** [comment]
Thank you, much appreciated!!

**Comment by tonykaralis** [comment]
Closes #39

**Pull request merged**
