### PR TITLE
Postgresql: Added ColumnExpression BigSerial and SmallSerial

### PR DESCRIPTION
**Pull request by gfoidl**
Fixes https://github.com/JasperFx/weasel/issues/76

### CODE REVIEW

**Comment by gfoidl** [comment]
I'll look into the failure tomorrow when I can use a Postgres-DB.

**Comment by mysticmind** [comment]
@gfoidl I restarted the CI tests again, it is green now. Looks like a blinking test so nothing to check further from your end.

**Comment by gfoidl** [comment]
@mysticmind thank you!

**Review by mysticmind — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
