### PR TITLE
Add support for creating views in postgres

### PR DESCRIPTION
**Pull request by smbecker**

### CODE REVIEW

**Review by oskardudycz — APPROVED** [review]
Thank you, @smbecker, that's an excellent addition!

**Comment by smbecker** [comment]
Thanks for merging but I must be missing something because I don't see this commit on the master branch

**Comment by oskardudycz** [comment]
@smbecker good catch; I have no idea what has happened o_O Maybe I messed something up with force pushes. Fixing that in https://github.com/JasperFx/weasel/pull/86, and sorry for the confusion!

**Comment by oskardudycz** [comment]
It's released now as part of `6.0.0-rc.2`.

**Pull request merged**
